CREATE TABLE [dbo].[Contact_Custom]
(
[SSB_CRMSYSTEM_ACCT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSB_CRMSYSTEM_CONTACT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSID_Winner] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_Ids] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimCustIDs] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssbcrmsystem_RecordType] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssbcrmsystemssidwinnersourcesystem] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TMSuite_Ids] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobilephone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ownerid] [uniqueidentifier] NULL,
[owneridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_category] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientheadline] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientarchticstag] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientpremiumsalesperson] [uniqueidentifier] NULL,
[str_clientpremiumserviceperson] [uniqueidentifier] NULL,
[str_BearsDirectEmailList] [bit] NULL,
[str_BearsPremiumEmailList] [bit] NULL,
[str_vamosbearsemaillist] [bit] NULL,
[str_ExclusiveBearsEventsEmailList] [bit] NULL,
[str_bearsinthecommunityemaillist] [bit] NULL,
[str_bearsproshopemaillist] [bit] NULL,
[str_bearssurveysemaillist] [bit] NULL,
[str_singlegameticketslist] [bit] NULL,
[str_seasonticketslist] [bit] NULL,
[str_seasonprioritylist] [bit] NULL,
[str_groupticketslist] [bit] NULL,
[str_premiumseatingoptions] [bit] NULL,
[str_accountattribute1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute10] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute11] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute12] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute13] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute14] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute15] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute16] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute17] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute18] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute19] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute20] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute5] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute6] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute7] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute8] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_accountattribute9] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_sthtenure] [int] NULL,
[str_clientsecondaryaccts] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomerid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssb_gamesmissed_nonsuites] [int] NULL,
[new_ssb_gamesmissed_suites] [int] NULL,
[new_append_abinumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_append_businesscreditscore] [int] NULL,
[new_append_businesscreditscoredescription] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_append_businesslocationtype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_append_company] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_append_individualfirmdescription] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_append_infogroupmatchpass] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_append_locationemploymentsize] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_append_locationsalesvolume] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_append_primarysiccode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_append_primarysiccodedescription] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_append_secondarysiccode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_append_secondarysiccodedescription] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_secondarycontact] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_eloquaticketrequesttimestamp] [datetime] NULL,
[new_eloquaticketrequesttype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ticketsalesperson] [uniqueidentifier] NULL,
[str_prioritylistcategory] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_othercategory] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_DueAmount] [decimal] (18, 6) NULL,
[birthdate] [date] NULL
)
GO
ALTER TABLE [dbo].[Contact_Custom] ADD CONSTRAINT [PK_Contact_Custom] PRIMARY KEY CLUSTERED  ([SSB_CRMSYSTEM_CONTACT_ID])
GO
