CREATE TABLE [stg].[CRM_Settings]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[ClientName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CRM_Platform] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MonitoringEnabled] [bit] NULL,
[HasContact] [bit] NULL,
[ProdcopyContactTable] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasAccount] [bit] NULL,
[ProdcopyAccountTable] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasTicketTransaction] [bit] NULL,
[ProdcopyTransactionTable] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasPatron] [bit] NULL,
[ProdcopyPatronTable] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntegrationUser] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasCase] [bit] NULL,
[ProdcopyCaseTable] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasPhoneCall] [bit] NULL,
[ProdcopyPhoneCallTable] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasEmail] [bit] NULL,
[ProdcopyEmailTable] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasOpportunity] [bit] NULL,
[ProdcopyOpportunityTable] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasMultipleLoadViews_Contact] [bit] NULL,
[HasMultipleLoadViews_Account] [bit] NULL,
[ContactStdUpdateCount] [int] NULL,
[ContactStdUpdateAvg] [int] NULL,
[ContactStdUpdateRunCount] [int] NULL,
[ContactStdUpdateView1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactStdUpdateView2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactStdUpsertCount] [int] NULL,
[ContactStdUpsertAvg] [int] NULL,
[ContactStdUpsertRunCount] [int] NULL,
[ContactStdUpsertView1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactStdUpsertView2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactCustomCount] [int] NULL,
[ContactCustomAvg] [int] NULL,
[ContactCustomRunCount] [int] NULL,
[ContactCustomView1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactCustomView2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountStdUpdateCount] [int] NULL,
[AccountStdUpdateAvg] [int] NULL,
[AccountStdUpdateRunCount] [int] NULL,
[AccountStdUpdateView1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountStdUpdateView2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountStdUpsertCount] [int] NULL,
[AccountStdUpsertAvg] [int] NULL,
[AccountStdUpsertRunCount] [int] NULL,
[AccountStdUpsertView1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountStdUpsertView2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountCustomCount] [int] NULL,
[AccountCustomAvg] [int] NULL,
[AccountCustomRunCount] [int] NULL,
[AccountCustomView1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountCustomView2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportingDatabase] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IntegrationDatabase] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProdcopySchema] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactStdResultsTable] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactStdResultsCount] [int] NULL,
[ContactStdResultsErrorCount] [int] NULL,
[ContactCustomResultsTable] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactCustomResultsCount] [int] NULL,
[ContactCustomResultsErrorCount] [int] NULL,
[AccountStdResultsTable] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountStdResultsCount] [int] NULL,
[AccountStdResultsErrorCount] [int] NULL,
[AccountCustomResultsTable] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountCustomResultsCount] [int] NULL,
[AccountCustomResultsErrorCount] [int] NULL,
[RunCount] [int] NULL,
[LastRunStart] [datetime] NULL,
[LastRunEnd] [datetime] NULL,
[Active] [bit] NULL CONSTRAINT [DF__CRM_Setti__Activ__0EF836A4] DEFAULT ((0)),
[NotificationRecipients] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AM] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasHEDA] [bit] NULL,
[HasHardDeletion] [bit] NULL,
[LoadDateField] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProdcopyDaysBack] [int] NULL,
[ContactProdcopyModifiedCount] [int] NULL,
[ContactProdcopyCreatedCount] [int] NULL,
[ContactProdcopyModifiedbySSBCount] [int] NULL,
[ContactProdcopyCreatedbySSBCount] [int] NULL,
[ContactLoadDateCount] [int] NULL,
[AccountProdcopyModifiedCount] [int] NULL,
[AccountProdcopyCreatedCount] [int] NULL,
[AccountProdcopyModifiedbySSBCount] [int] NULL,
[AccountProdcopyCreatedbySSBCount] [int] NULL,
[AccountLoadDateCount] [int] NULL,
[HasContactMerge] [bit] NULL,
[HasAccountMerge] [bit] NULL,
[ContactMergeResultsTable] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountMergeResultsTable] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactMergeResultsCount] [int] NULL,
[ContactMergeResultsErrorCount] [int] NULL,
[AccountMergeResultsCount] [int] NULL,
[AccountMergeResultsErrorCount] [int] NULL
)
GO
ALTER TABLE [stg].[CRM_Settings] ADD CONSTRAINT [PK__CRM_Sett__65800DA1341562B9] PRIMARY KEY CLUSTERED  ([ClientName])
GO
